const colors = {
  light: {
    text: "#050508",
    tint: "#8b5cf6",
    background: "#f5f3ff",
    foreground: "#1f1430",
    card: "#ffffff",
    cardForeground: "#1f1430",
    primary: "#7c3aed",
    primaryForeground: "#ffffff",
    secondary: "#ede9fe",
    secondaryForeground: "#4c1d95",
    muted: "#f5f3ff",
    mutedForeground: "#6b7280",
    accent: "#8b5cf6",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e9e5f5",
    input: "#e9e5f5",
    success: "#10b981",
    warning: "#f59e0b",
  },

  dark: {
    text: "#f3f4f6",
    tint: "#8b5cf6",
    background: "#050508",
    foreground: "#f3f4f6",
    card: "#0d0d15",
    cardForeground: "#f3f4f6",
    primary: "#8b5cf6",
    primaryForeground: "#ffffff",
    secondary: "#1a1a2e",
    secondaryForeground: "#c4b5fd",
    muted: "#0d0d15",
    mutedForeground: "#9ca3af",
    accent: "#8b5cf6",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#1f1f2e",
    input: "#1f1f2e",
    success: "#10b981",
    warning: "#f59e0b",
  },

  radius: 12,
};

export default colors;
